server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
    gateway:
      # Configuración de rutas usando las variables de entorno de Render
      routes:
        - id: msvc-user
          uri: http://${SERVICE_USER_HOST}:8080 # <--- ¡AQUÍ USAMOS LA VARIABLE!
          predicates:
            - Path=/api/users/**, /api/auth/**

        - id: msvc-task
          uri: http://${SERVICE_TASK_HOST}:8080
          predicates:
            - Path=/api/tasks/**

        - id: msvc-note
          uri: http://${SERVICE_NOTE_HOST}:8080
          predicates:
            - Path=/api/notes/**

        - id: msvc-event
          uri: http://${SERVICE_EVENT_HOST}:8080
          predicates:
            - Path=/api/events/**

      discovery:
        locator:
          enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

jwt:
  secret: myVerySecretKeyForAppAgenditaTaskService2024
